### ISSUE TITLE
샘플앱에서 ViewPagerWithTabLayout 기능 관련 문의 있습니다.,

### ISSUE THREAD

**Issue by Gurumigun** [naverz/Antonio#6]
일단 너무 괜찮은 라이브러리 제공에 감사합니다.

현재 ViewPager2 를 사용해서 개발 중이고 Tablayout 과 같이 사용하려고 합니다.

샘플앱에서 궁금한게 있습니다.

@MappedWithViewDependency(viewClass = ViewHolderPagerWithTabLayout::class)
class ViewPagerWithTabLayout<T : AntonioModel>(val viewPagerState: ViewPagerState<T>) :
    AntonioModel

샘플 앱에서 보면 위와같이  MappedWithViewDependency 으로 viewHolder 의 의존성을 주는거 같은데
라이브러리 배포된 것에서는 MappedWithViewDependency를 찾아보기 어렵더라구요.

샘플에서 처럼 ViewHolderPagerWithTabLayout 처럼 AntonioViewHolder를 상속받아 사용하고 싶은데 라이브러리 사용해서는 어떻게 적용할 수 있을까요 ?

**Comment by LakeLab** [comment]
안녕하세요 @Gurumigun 님.
우선 라이브러리에 관심을 갖고 문의 주셔서 감사드립니다! :) 

현재 내부적으로 AnnotationProcessor를 KSP로 전환 중에 있어 현재 Annotation 지원을 잠시 중단중에 있습니다. 😢 
허나 Annotation 외의 방법으로 ViewHolder를 직접 구현 하여 Antonio를 사용 하실 수 있으신데요!

[Usage without data binding(https://github.com/naverz/Antonio/wiki/Usage-without-data-binding) 페이지]에서 해당 방법 확인 하실 수 있습니다! 

확인 후 추가적으로 궁금하신 사항이 있으시다면 언제든지 말씀주세요 😃 
감사합니다!

**Comment by Gurumigun** [comment]
ViewHolder를 Custom 할려면 ViewContainer 를 사용하면 되는군요 ㅎㅎ
