### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Gurumigun** [naverz/Antonio#7]
**버그 상황**
androidx.activity:activity:1.7.0, androidx.activity:activity-compose:1.7.0, and androidx.activity:activity-ktx:1.7.0에서 
AntonioAutoBindingViewHolder2에서 override 하는 getlifecycle 가 변경되어 빌드가 안됩니다.

public interface LifecycleOwner {
    /**
     * Returns the Lifecycle of the provider.
     *
     * @return The lifecycle of the provider.
     */
    @NonNull
    Lifecycle getLifecycle();
}

interface 가 변경되었습니다. 

public interface LifecycleOwner {
    /**
     * Returns the Lifecycle of the provider.
     *
     * @return The lifecycle of the provider.
     */
    public val lifecycle: Lifecycle
}
로 변경되었습니다

**재현경로**
예시)

1. '...' 로 간다
2. '....' 를 클릭한다
3. '....' 로 스크롤은 내린다.
4. 에러 발생

**기대 상황**
원래 기대하셨던 상황 공유 부탁드립니다.

**Screenshots**
스크린샷을 올려주시면 매우 큰 도움이 됩니다.

**디바이스 종류:**
 - Device: [e.g. Pixel 5]
 - OS: [e.g. Android 12]

**추가 정보**
에러 로그나 기타 사항.

**Comment by LakeLab** [comment]
제보 감사드립니다. 곧 해결한 버전 배포 진행할수 있도록 하겠습니다.
